### ISSUE TITLE
doesn't start "run.bat" (Windows 10)

### ISSUE THREAD

**Issue by ymkim2** [ricotabor/opendrop#1]
I just installed Python Anaconda 3 and Opencv3.0, on Windows 10. I followed instruction of copy one file on site-package folder. And I double clicked the "run.bat" file. However, it doesn't start. Please help.
Thank you in advance.

**Comment by jdber1** [comment]
Hello,

Do you get an error message, or does nothing happen at all?
If you are getting an error message are you able to send it to us?
Unfortunately we have not yet tested OpenDrop on Windows 10, but we are
hoping to very shortly.

Regards,
Joe

**Comment by ymkim2** [comment]
Hello Joe,

There was no error message. It doesn't happen anything at all.

I hope it's not windows 10 compatibility issue (I have already suffered
enough).

Thanks,
Yongman

-------------------------------------------------------------
Yongman Kim, Ph. D
Senior Scientific Engineer Associate
Earth Science Division
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720
Tel.: 510-486-4566
Email: ymkim@lbl.gov
---------------------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

Ok thanks for that. We have not yet got our hands on a machine running
Windows 10. Let us track one down and we will get you instructions on how
to run opendrop on your computer (hopefully by the end of the year).

Regards,
Joe

**Comment by jdber1** [comment]
Dear Yongman,

We have located a computer running Windows 10, and have had no trouble
setting up OpenDrop to run correctly.
Are you able to run OpenDrop from a command prompt so that we can see what
error you are getting?
To do so, right click on the Windows icon, and choose "Command Prompt".
Next, cd to the directory where your installation resides. Finally, type
"python opendrop.py" to run OpenDrop. An error message should be displayed:
can you please send this so we can correctly diagnose the problem?

Regards,
Joe

**Comment by ymkim2** [comment]
Hello Joe,

Happy New Year~!

Please see the screen image attached, error message from the "Command
Prompt" I checked the "Modules" folder, and there is 'de_YoungLaplace.py'
and 'de_YoungLaplace.pyc' file.

Thanks,
Yongman


[image: Inline image 1]




-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

Happy new year to you too. I can't see any image - are you able to reattach?
If you are having problems with github, email the image directly to opendropdev@gmail.com.

Cheers,
Joe

**Comment by ymkim2** [comment]
Here is the image.

[image: Inline image 1]

And, the error message says:

Trackback (most recent call last):
File "opendrop.py", line 16, in <module>
from modules, classes import ExperimentalSetup, ExperimentalDrop, DropData,
Tolerances
File "C:\options\opendrop-1.1\modules\classes.py", line 3, in <module>
from de_YoungLaplace import ylderiv
ImportError: No module named 'de_YoungLaplace'

Thanks,
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

In the screenshot you sent, the backslashes in the pathname appear as symbols. From previously reported issues, this seems to be a locale/language issue. It appears as though python is not recognising the pathname due to the presence of this symbol.  Are you able to change this so that the path appears correctly and then retry?

Cheers,
Joe

**Comment by ymkim2** [comment]
Hello Joe,

Even after the locale/language was changed to English only, I have the same
error message (except with backslashes instead of symbols).

Please see the image below.

[image: Inline image 1]



-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by ymkim2** [comment]
Hi Yongman,

Ok thanks for that. Can you tell me a little more about your installation
procedure? Did you follow the instructions in our readme, or did you
already have python installed?

Also, from the command prompt, can you:
1) run python with the command "python"
2) type "import sys"
3) type "print (sys.version)"
4) send us the output from this command

Cheers,
Joe

**Comment by ymkim2** [comment]
Hello Joe,

I followed the readme instruction, since it was my very first time to use
the python program.

And the python prints:

3.5.1 Anaconda 2.4.1 (64-bit) (default, Dec 7 2015, 15:00:12) [MSC v.1900
64 bit (AMD64)]

[image: Inline image 1]

Thanks,
Yongman



-------------------------------------------------------------
Yongman Kim, Ph. D
Senior Scientific Engineer Associate
Earth Science Division
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720
Tel.: 510-486-4566
Email: ymkim@lbl.gov
---------------------------------------------------------------

**Comment by ymkim2** [comment]
Hi Yongman,

You have installed python 3.5, which may explain the issues you are having.
We recommend that you install python 2.7 (we have not done any testing with
3.5). Can you uninstall your python distribution and reinstall using the
python 2.7 package available on the Anaconda website (see our readme on
github), and then try again?

Cheers,
Joe

**Comment by ymkim2** [comment]
Hello Joe,

I installed python 2.7.11, and tried it again. However, I got new error
message that no module named numpy.

[image: Inline image 1]

Thanks,
Yongman



-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

This usually occurs when you have two existing python versions, see here for example: http://stackoverflow.com/questions/26318995/installing-numpy-via-anaconda-in-windows.

Did you uninstall python 3.5 correctly and completely? That seems to be the issue here.

Cheers.
Joe

**Comment by ymkim2** [comment]
I had uninstalled python 3.5 from Windows program setting menu, and it said
completely installed followed by rebooting. After then, I installed python
2.7 and again rebooting. I couldn't see any sign of python 3.5, so it seems
it had been uninstalled correctly and completely.

I tried to set the full path as the link suggested, but still I have "no
module named numpy" error. By the way, when I searched "numpy", there is no
folder nor file named numpy. I seemd I have to add numpy.



-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

Where is your python installation? Do you have this folder:
C:/Python27/lib/site-packages/?
Or this folder C:/Anaconda2/Lib/site-packages/?
There will be a numpy subfolder within the site-packages folder of your
Python 2.7 installation. Can you check for me please?
Also, although you have uninstalled Python 3.5, does a Python35 or
Anaconda3 folder still exist on your C: drive?

Cheers,
Joe

**Comment by ymkim2** [comment]
Hell Joe,

I have "C:\Python27\Lib\site-packages"

By the way, I searched, and it confirmed that I don't have Python35 nor
Anaconda3 folder.

Thanks,
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by ymkim2** [comment]
there is no numpy folder under site-packages, either.

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

Is there a numpy subfolder?

Cheers,
Joe

**Comment by jdber1** [comment]
Hi Yongman,

A full anaconda installation comes with numpy. However, you can install it
from the command line using the command "conda install numpy". Try this and
see what happens.

Cheers,
Joe

**Comment by ymkim2** [comment]
Hello Joe,

nothing happened but "not recognized" error. I tried "anaconda install
numpy" and "python install numpy", but only error messages showed.

Thanks,
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

The command is conda, not anaconda.
Try "conda install numpy".

Joe

**Comment by ymkim2** [comment]
Hello Joe,

Yes, I had tried conda the first, but nothing happened.

Thanks,
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

Can you tell me exactly which Anaconda package you installed? Can you
copy/paste the filename?
It seems as if your installation has not worked.

Cheers,
Joe

**Comment by ymkim2** [comment]
Hello Joe,

It's a windows installer package "python-2.7.11.msi" from the python
website.

Thanks,
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

You need to install the Anaconda 2.7 distribution as explained in the
readme on github. The website is: https://www.continuum.io/downloads.
Uninstall your python 2.7 first.

Cheers,
Joe

**Comment by ymkim2** [comment]
Hello Joe,

I uninstalled python 2.7 and then installed Anaconda 2.7. After all these,
when I tried again, it seems working in the beginning. However, I
encountered a blue screen error with "Kernel_Security_Check_Failure"
message soon after I ran opendrop. It happened random like sometimes when I
selected drop area, sometimes when it calculated, sometimes when I selected
an image. Please advise.

Thanks,
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by ymkim2** [comment]
after I got the blue screen error (Kernel_Security_Check_Failure) several
times, now I have the following error from opendrop.
I'm not sure what went wrong...

Thanks,
Yongman

[image: Inline image 1]


-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

Can you send me your parameters.csv file in the modules subfolder?
What values are you using in the GUI for drop properties etc? Does your
path to read/write contain any non-standard characters?

Try deleting the parameters.csv file and then try again.

Cheers,
Joe

**Comment by ymkim2** [comment]
Hello Joe,

Please find the parameters.csv file attached. I changed the needle diameter
value (to 1.5875) only, and there is no non-standard characters in the path.

Thanks,
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Hi Yongman,

It is not attached - send directly to opendropdev@gmail.com, or copy/paste
into email. Did you try deleting the file and running OpenDrop again? It
sounds like you have a memory leak somewhere, which we may not be able to
help with if it keeps persisting.

Joe

**Comment by ymkim2** [comment]
Please see the file attached. When I opened the file, I could see it
doesn't content anything inside.

After deleting the "parameters.csv" file, it seems working now.

Thanks a lot~!
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by jdber1** [comment]
Good to hear Yongman - good luck using the software.

**Comment by ymkim2** [comment]
Hello Joe,

I need your help again. I tired to run opendrop-1.1 with the images
attached. The program itself looks running okay, but the results are pretty
odd. The IFT numbers are all different even the droplet is the same one.
And, 3 of the IFT results are far away from reasonable range. If I use the
table from Adamson's book (in 1960), the IFT calculation becomes around 30
mN/m, which it looks more reasonable. I checked the manual but I couldn't
figure out what might go wrong.

By the way, the first image is a RGB image from a camera, and the others
are converted image using imageJ from the original one (32 bit gray,
cropped droplet & needle area, and binary with filled). The needle diameter
is 1.5875 mm, and the density of droplet is 1010.7 kg/m3. The droplet fluid
is 0.1 M NaCl solution saturated with supercritical CO2 at 100 bar 45 C.
And its hanging in the supercritical CO2 at the same P (100 bar) & T (45 C).

Please advise.

Thank you,
Yongman

[image: Inline image 1]

[image: Inline image 2]

[image: Inline image 3]  [image: Inline image 4]

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by ymkim2** [comment]
Hi Yongman,

I expect that this arises from an anomalously low density difference
between the drop and the continuous phase. What value are you using for
continuous phase density?

cheers,
Rico

---
Rico Tabor

**Comment by ymkim2** [comment]
Hello Rico,

Oops, I didn't enter any number there. However, even after I entered the
continuous density of 498.25 kg/m3 (scCO2 density at 100 bar, 45C, from
NIST database), the IFT numbers are still far from a reasonable range.
Please see the second section in the attached worksheet. And, please let me
know what other parameters I may check.

Thank you,
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by ymkim2** [comment]
Hi Yongman,

If you are sure about the densities (as I can't check them for you) then I
would suggest the next place to look is the way the image is lit. It looks
as though the backlight is too strong for the camera, and you are getting
significant saturation of pixels around the edge of the drop. This causes
the true edge to be lost, making the drop (and possibly also needle) appear
smaller than it really is.

I would try to take an image with much lower back-light intensity to see if
this helps?

The only other possibility is that the needle diameter is incorrect - these
are really the only parameters which you can change! The rest just lies in
the physics of the problem.

cheers,
Rico

---
Rico Tabor

**Comment by ymkim2** [comment]
Hello Rico,

I'm pretty sure about density values, and the images were taken with the
minimum back light. As I mentioned in earlier email, the IFT number
calculated from the same image is about 30 mN/m. But, with opendrop, I have
about 88-97 mN/m (if I discard image #4, since its Worthing number is
0.33). If I used the same image, I think I should have similar IFT number
(regardless of the methods I used). As you mentioned, only a few parameters
I enter, and the rest lies in the physics of the problem.

Thank you,
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------

**Comment by ymkim2** [comment]
Hi Yongman,

The image is most likely to be the problem. You can see at the bottom of
the drop, it appears to 'bulge' aphysically. This is obviously an optical
artefact that indicates the image is not suitable for fitting, due to the
lighting issue mentioned above (too much backlight or too high contrast
setting on camera). If this is the lowest backlight setting, perhaps you
could use a neutral density filter to reduce the amount of light getting
through? Or change the camera settings (reduce exposure time or stop it
autoexposing).

cheers,
Rico

---
Rico Tabor

**Comment by ymkim2** [comment]
Hello Rico,

Thank you for the suggestions. I'll try them for getting better images.

Thank you,
Yongman

-------------------------------------------------
Yongman Kim, Ph. D.
Senior Scientific Engineer Associate
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 74R316C
Berkeley, CA 94720, USA
Phone: 510-486-4566
Email: ymkim@lbl.gov
-------------------------------------------------
