### ISSUE TITLE
Fails to converge

### ISSUE THREAD

**Issue by kc112358** [ricotabor/opendrop#2]
I've double checked all the physical parameters I provided for the density of each phase, and for the inner diameter of the needle. However, the software is failing to converge on any pendant drop image I've taken. Is there any way to understand why by observing the image?

![cyclohexane softened profile](https://cloud.githubusercontent.com/assets/17934372/13888707/770e7cbc-ed08-11e5-8be3-89d5eac93dc6.png)
![cyclohexane softened residuals](https://cloud.githubusercontent.com/assets/17934372/13888713/81d344ca-ed08-11e5-87c5-c5a07c8d5789.png)
![capture](https://cloud.githubusercontent.com/assets/17934372/13888740/a6ab855a-ed08-11e5-860a-f928be3e3b5e.JPG)

**Comment by ricotabor** [comment]
Hi! 

Your drop image looks a bit grainy at the edges (i.e. the drop profile isn't smooth) This could be the issue, but without the clean image it's hard to check. Also, you should use the outer diameter of the needle (as this calibrates the length-scale, it's not a fitting parameter/part of the Young-Laplace solver), although this isn't the problem here, it will give you inaccurate results to use the needle inner diameter.

If you send a typical image (without the attempted fit overlaid) to opendrop.dev@gmail.com then we can do some troubleshooting and get back to you with more info on how to fix this.

cheers,
Rico

**Comment by kc112358** [comment]
Hi,

Thank you for the information about the needle diameter. I'll correct that.

My equipment (and camera) are not the best quality. I attempted to clean up
the image by removing the background, which is likely why the edges are
grainy. I've attached an un-edited image as well as an edited image with no
profile fitting.

Thank you,
Killian

On Fri, Mar 18, 2016 at 5:02 PM, ricotabor <notifications@github.com> wrote:

> Hi!
>
> Your drop image looks a bit grainy at the edges (i.e. the drop profile
> isn't smooth) This could be the issue, but without the clean image it's
> hard to check. Also, you should use the outer diameter of the needle (as
> this calibrates the length-scale, it's not a fitting parameter/part of the
> Young-Laplace solver), although this isn't the problem here, it will give
> you inaccurate results to use the needle inner diameter.
>
> If you send a typical image (without the attempted fit overlaid) to
> opendrop.dev@gmail.com then we can do some troubleshooting and get back
> to you with more info on how to fix this.
>
> cheers,
> Rico
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ricotabor/opendrop/issues/2#issuecomment-198572610>
>



-- 
Killian O'Connell
*Colorado State University *
*Biochemistry & Molecular Biology, 2015*
Tel: (434) 466-2441
killian.oconnell137@gmail.com

**Comment by ricotabor** [comment]
Hi Killian,

Can you please forward the images to opendrop.dev@gmail.com - for some reason attachments don't seem to work on the github message thingy.

cheers,
Rico

**Comment by kc112358** [comment]
Hi Rico,

Of course. I've sent them to the address you provided. Hope it works.

On Mon, Mar 21, 2016 at 4:08 PM, ricotabor <notifications@github.com> wrote:

> Hi Killian,
>
> Can you please forward the images to opendrop.dev@gmail.com - for some
> reason attachments don't seem to work on the github message thingy.
>
> cheers,
> Rico
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ricotabor/opendrop/issues/2#issuecomment-199509848>
>



-- 
Killian O'Connell
*Colorado State University *
*Biochemistry & Molecular Biology, 2015*
Tel: (434) 466-2441
killian.oconnell137@gmail.com

**Comment by ricotabor** [comment]
For future reference: we resolved this issue. It was the quality of the original image that caused problems with finding the droplet profile - specifically the diffuseness of the interface. This can be solved by binarising the image in ImageJ (or similar) and then proceeding, where the quality of fit becomes very good.
